# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from second_window import *


class Ui_Plotter(object):
    
    #second window function
    def open_sec_win(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Plotter):
        Plotter.setObjectName("Plotter")
        Plotter.resize(871, 589)
        Plotter.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.columnView_2 = QtWidgets.QColumnView(Plotter)
        self.columnView_2.setGeometry(QtCore.QRect(0, 0, 871, 131))
        self.columnView_2.setObjectName("columnView_2")
        self.label = QtWidgets.QLabel(Plotter)
        self.label.setGeometry(QtCore.QRect(80, 20, 701, 81))
        font = QtGui.QFont()
        font.setFamily("dsrom10")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dnd = QtWidgets.QColumnView(Plotter)
        self.dnd.setGeometry(QtCore.QRect(70, 170, 751, 231))
        self.dnd.setMouseTracking(False)
        self.dnd.setAcceptDrops(True)
        self.dnd.setStyleSheet("background-color: rgb(97, 53, 131);\n"
"background-color: rgb(119, 118, 123);\n"
"border-color: rgb(99, 69, 44);")
        self.dnd.setDragEnabled(True)
        self.dnd.setDragDropOverwriteMode(True)
        self.dnd.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.dnd.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.dnd.setObjectName("dnd")
        self.label_2 = QtWidgets.QLabel(Plotter)
        self.label_2.setGeometry(QtCore.QRect(320, 170, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(246, 245, 244);")
        self.label_2.setObjectName("label_2")
        self.importing = QtWidgets.QPushButton(Plotter)
        self.importing.setGeometry(QtCore.QRect(340, 470, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.importing.setFont(font)
        self.importing.setStyleSheet("background-color: rgb(192, 28, 40);")
        self.importing.setObjectName("importing")
        self.label_3 = QtWidgets.QLabel(Plotter)
        self.label_3.setGeometry(QtCore.QRect(400, 440, 91, 19))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Plotter)
        self.pushButton.setGeometry(QtCore.QRect(720, 550, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        #second window click button (proceed button)
        # self.pushButton.clicked.connect(self.open_sec_win)

        self.label_5 = QtWidgets.QLabel(Plotter)
        self.label_5.setGeometry(QtCore.QRect(660, 510, 181, 19))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Plotter)
        QtCore.QMetaObject.connectSlotsByName(Plotter)

    def retranslateUi(self, Plotter):
        _translate = QtCore.QCoreApplication.translate
        Plotter.setWindowTitle(_translate("Plotter", "Dialog"))
        self.label.setText(_translate("Plotter", "PYTHON PLOTTER"))
        self.label_2.setText(_translate("Plotter", "   DRAG AND DROP"))
        self.importing.setText(_translate("Plotter", "IMPORT CSV FILE"))
        self.label_3.setText(_translate("Plotter", "OR CLICK ->"))
        self.pushButton.setText(_translate("Plotter", "Proceed"))
        self.label_5.setText(_translate("Plotter", "File Import check"))
