# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Plotter")
        Dialog.resize(871, 589)
        self.columnView_2 = QtWidgets.QColumnView(Dialog)
        self.columnView_2.setGeometry(QtCore.QRect(0, 0, 871, 131))
        self.columnView_2.setObjectName("columnView_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 20, 701, 81))
        font = QtGui.QFont()
        font.setFamily("dsrom10")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dnd = QtWidgets.QColumnView(Dialog)
        self.dnd.setGeometry(QtCore.QRect(70, 200, 751, 291))
        self.dnd.setMouseTracking(False)
        self.dnd.setAcceptDrops(True)
        self.dnd.setStyleSheet("background-color: rgb(97, 53, 131);\n"
"background-color: rgb(119, 118, 123);\n"
"border-color: rgb(99, 69, 44);")
        self.dnd.setDragEnabled(True)
        self.dnd.setDragDropOverwriteMode(True)
        self.dnd.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.dnd.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.dnd.setObjectName("dnd")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 200, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(246, 245, 244);")
        self.label_2.setObjectName("label_2")
        self.importing = QtWidgets.QPushButton(Dialog)
        self.importing.setGeometry(QtCore.QRect(350, 560, 141, 27))
        self.importing.setStyleSheet("background-color: rgb(192, 28, 40);")
        self.importing.setObjectName("importing")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(380, 520, 91, 19))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "PYTHON PLOTTER"))
        self.label_2.setText(_translate("Dialog", "   DRAG AND DROP"))
        self.importing.setText(_translate("Dialog", "IMPORT CSV FILE"))
        self.label_3.setText(_translate("Dialog", "OR CLICK ->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
